name: Execute API Tests

# on:
#   pull_request:
on:
  push:
    branches:
      - main

jobs:
  text_execution:
    runs-on: ubuntu-latest
    steps:
      - name: üõé Checkout
        uses: actions/checkout@v2
      # - name: execute api in docker üê≥
      #   run: docker-compose up
      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
      - name: Make Directory for results
        run: mkdir -p TestResults
        # it's also possible to supply specific environment variables by using the -e argument here. e.g. -e ./Internal_Staging.postman_environment.json
      - name: Run POSTMAN collection
        run: |
          newman run Todos\ API.postman_collection.json -r htmlextra --reporter-htmlextra-export TestResults/htmlreport.html --reporter-htmlextra-darkTheme
      - name: Output the run Details
        uses: actions/upload-artifact@v2
        with:
          name: ReportOutput
          path: TestResults
